version: '3.7'

services:
  server:
    image: nginx
    container_name: invoiceninja_server
    restart: always
    env_file: stack.env
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    networks:
      - invoiceninja
      - traefik

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    container_name: invoiceninja_app
    restart: always
    volumes:
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mysql:8
    container_name: invoiceninja_db
    restart: always
    env_file: stack.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja


networks:
  invoiceninja:
  traefik:
    external: true
