version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: invoiceninja-nginx
    volumes:
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - invoiceninja-public:/var/www/app/public:ro
    depends_on:
      - invoiceninja
    networks:
      - invoiceninja
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invoiceninja.rule=host(`ininja.soarelly.com`)"
      - "traefik.http.routers.invoiceninja.entrypoints=websecure"
      - "traefik.http.routers.invoiceninja.tls=true"
      - "traefik.http.routers.invoiceninja.tls.domains[0].main=soarelly.com"
      - "traefik.http.routers.invoiceninja.tls.domains[0].sans=*.soarelly.com"
      - "traefik.http.routers.invoiceninja.tls.certresolver=godaddy"
      - "traefik.http.routers.invoiceninja.middlewares=oauth"

  invoiceninja:
    image: invoiceninja/invoiceninja:5.8
    container_name: invoiceninja
    restart: unless-stopped
    volumes:
      - invoiceninja-public:/var/www/app/public:rw,delegated
      - invoiceninja-storage:/var/www/app/storage:rw,delegated
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - invoiceninja

  mariadb:
    image: linuxserver/mariadb:10.6.10
    container_name: invoiceninja-mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config/mysql:/config
    networks:
      - invoiceninja

volumes:
  invoiceninja-public:
  invoiceninja-storage:


networks:
  invoiceninja:
  traefik:
    external: true
